import routerx from 'express-promise-router';
import userRouter from './UserRoutes';
import rolRouter from './RolRoutes';
import categoriaRouter from './CategoriaRoutes';
import productoRouter from './ProductoRoutes';
import equipoDeTrabajoRouter from './EquipoDeTrabajoRoute';
import metaEquipoTrabjoRouter from './MetaEquipoTrabajoRoutes';
import metaUsuarioRouter from './MetaUsuarioRoutes';
import coleccionesRouter from './ColeccionRoutes';
import listaPrecioRouter from './ListaPreciosRoutes';
import almacenes from './AlmacenesRoutes';
import Pais from './PaisRoutes';
import MarcaRouter from './MarcaRoutes';
import SociosNegocioRouter from './SociosNegocioRoutes';
import SociosNegocioUsuariosRouter from './SociosNegocioUsuariosRoutes';
import SociosNegocioDireccionesRouter from './SociosNegocioDireccionesRoutes';
import productoStockRouter from './ProductoStockRoutes';
import FilesRoutes from './FilesRoutes';
import CarritoCompraRoutes from './CarritoDeComprasRoutes';
import PromocionesRoutes from './PromocionesRoutes';
import ControlMaestroMultipleRouter from './ControlesMaestrosRoutes';
import CompraFinalizadaRoutes from './CompraFinalizadaRoutes'; 
import CotizacionProyecto from './CotizacionProyectoRoutes';
import Atributos from './AtributosRoutes';
import RawIntegraciones from './RawIntegracionesRoutes';
import IntegracionesInfoTransfer from './IntegracionesInfoTransferRoutes';
import FacturasRoutes from './FacturasRoutes';
import Fleteras from './FleterasRoutes';
import SapMetodosPago from './SapMetodosPagoRoutes';
import SapFormasPago from './SapFormasPagoRoutes';
import ProductosKitsRoutes from './ProductosKitsRoutes';
import ProductosKitsComponentesRoutes from './ProductosKitsComponentesRoutes';
import faqsRoutes from './FaqsRoutes';
import BannersRoutes from './BannersRoutes';
import SlidersRoutes from './SlidersRoutes';
import ProveedoresRoutes from './ProveedoresRoutes';
import PaginaInstitucional from './PaginaInstitucionalesRoutes';
import CfdiRoutes from './CfdiRoutes';
import SolicitudDeCredito from './SolicitudDeCreditoRoutes';
import ContactoRoutes from './ContactoRoutes';
import WishListRoutes from './WishListRoutes';
import ResenasProductosRoutes from './ResenasProductosRoutes';
import testEmailController from '../controllers/PublicControllerTest';
import ConektaRoutes from './ConektaRoutes';
import PaqueteExpressRoutes from './PaqueteExpressRoutes';
import V2CarritoCompraRoutes from './V2CarritoDeComprasRoutes';
import V2PromocionesRoutes from './V2PromocionesRoutes';
import V2CuponesRoutes from './V2CuponesRoutes';
import CiudadesEstadosRoutes from './EstadosCiudadesRoutes';
import PoliticasEnvioRoutes from './PoliticasEnvioRoutes';
import NewsletterRoutes from './NewsLetterRoutes';
import CotizacionesRoutes from './CotizacionesRoutes';
import UsuariosProspectosRoutes from './UsuariosProspectosRoutes';

import ElasticsearchRoutes from './ElasticsearchRoutes';
import VendedoresRoutes from './VendedoresRoutes';
import GerentesRoutes from './GerentesRoutes';
import search from './search';

import sitemapRouter from './SitemapRoutes';
import ProyectosRoutes from './ProyectosRoutes';

import FinalizarCotizacionRoutes from './FinalizarCotizacionRoutes';

import ColeccionesRoutes from './ColeccionesRoutes';

const router = routerx();
router.use('/v1/sitemap', sitemapRouter);
router.use('/user', userRouter);
router.use('/rol', rolRouter);
router.use('/categoria', categoriaRouter);
router.use('/productos', productoRouter);
router.use('/equipo_de_trabajo', equipoDeTrabajoRouter);
router.use('/meta_equipo_trabajo', metaEquipoTrabjoRouter);
router.use('/meta_usuario', metaUsuarioRouter);
router.use('/colecciones', coleccionesRouter);
router.use('/listas_de_precios', listaPrecioRouter);
router.use('/almacenes', almacenes);
router.use('/pais', Pais);
router.use('/marcas', MarcaRouter);
router.use('/socio_negocio', SociosNegocioRouter);
router.use('/socio_negocio_usuarios', SociosNegocioUsuariosRouter);
router.use('/socio_negocio_direcciones', SociosNegocioDireccionesRouter);
router.use('/productos_stock', productoStockRouter);
router.use('/files', FilesRoutes);
router.use('/carrito_de_compras', CarritoCompraRoutes);
router.use('/promociones', PromocionesRoutes);
router.use('/controles_maestros', ControlMaestroMultipleRouter);
router.use('/compras_finalizadas', CompraFinalizadaRoutes);
router.use('/cotizaciones_proyectos', CotizacionProyecto);
router.use('/atributos', Atributos);
router.use('/rawintegraciones', RawIntegraciones);
router.use('/integraciones_info_transfer', IntegracionesInfoTransfer);
router.use('/facturas', FacturasRoutes);
router.use('/fleteras', Fleteras);
router.use('/sap_metodos_pago', SapMetodosPago);
router.use('/sap_formas_pago', SapFormasPago);
router.use('/productos_kits', ProductosKitsRoutes);
router.use('/productos_kits_componentes', ProductosKitsComponentesRoutes);
router.use('/faqs', faqsRoutes);
router.use('/banners', BannersRoutes);
router.use('/sliders', SlidersRoutes);
router.use('/proveedores', ProveedoresRoutes);
router.use('/paginas_institucionales', PaginaInstitucional);
router.use('/cfdi', CfdiRoutes);
router.use('/solicitudes_de_credito', SolicitudDeCredito);
router.use('/contacto', ContactoRoutes);
router.use('/wish_list', WishListRoutes);
router.use('/resenas_productos', ResenasProductosRoutes);
router.post('/test', testEmailController.testEmailPublic);
router.post('/orden', testEmailController.pruebaPedidoAprovado);
router.post('/rechazo', testEmailController.pruebaPagoRechazado);
router.get('/menu_admin', testEmailController.getAdmin);
router.get('/menu_usuario', testEmailController.getUsuario);
router.use('/conekta_internal_apis', ConektaRoutes);
router.use('/paquete_express', PaqueteExpressRoutes);
router.use('/v2_carrito_compras', V2CarritoCompraRoutes);
router.use('/v2_promociones', V2PromocionesRoutes);
router.use('/v2_cupones', V2CuponesRoutes);
router.use('/ciudades_estados', CiudadesEstadosRoutes);
router.use('/politicas_envio', PoliticasEnvioRoutes);
router.use('/newsletter', NewsletterRoutes);
router.use('/cotizaciones', CotizacionesRoutes);
router.use('/usuarios_prospectos', UsuariosProspectosRoutes);
router.use('/elasticsearch', ElasticsearchRoutes);
router.use('/vendedores', VendedoresRoutes);
router.use('/gerentes', GerentesRoutes);
router.use('/search', search);
router.use('/proyectos', ProyectosRoutes);
router.use('/finish-quotes', FinalizarCotizacionRoutes);
router.use('/collection', ColeccionesRoutes);
export default router;